# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Achivement
on:
  # Schedule daily updates
  schedule: [{cron: "10 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:         
      - name: Achivement
        uses: lowlighter/metrics@latest
        with:
          filename: achivement.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          base_indepth: yes
          config_timezone: Asia/Taipei
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          user: sum2do
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_fortune: yes
