# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Gernal-LO
on:
  # Schedule daily updates
#   schedule: [{cron: "20 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  # push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:         
      - name: Gernal L-O
        uses: lowlighter/metrics@latest
        with:
          filename: general_LO.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST }}
          output_action: gist
          repositories_forks: yes
          repositories_skipped: ${{ secrets.IGNORE }}
          # Options
          user: NTTUCSIE-111
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Asia/Taipei
          config_order: base.header, introduction, base.activity+community, base.repositories, lines, language, habbit , base.metadata
          repositories_affiliations: organization_member
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
          
#       - name: Checkout repository
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0
          
#       - name: out
#         run: |
#           set +e
#           git checkout metrics-renders
#           git config user.name github-actions[bot]
#           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
#           sudo mv /metrics_renders/* ./
#           git add --all
#           git commit -m "chore: push metrics"
#           git push
